version: '3.8'

services:
  app:
    build:
      context: .
      target: production  # Use the production stage for deployment
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/tenant-db
      - CORS_ORIGIN=http://0.0.0.0:3000
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge